import { useState } from "preact/hooks";
import type {
  RecipeWithDetails,
  CreateRecipeInput,
  IngredientInput,
  StepInput,
  TagInput,
} from "@recipes/shared";

interface Props {
  recipe?: RecipeWithDetails;
  onSubmit: (data: CreateRecipeInput) => Promise<void>;
  onCancel: () => void;
  submitLabel?: string;
}

interface FormIngredient extends IngredientInput {
  key: number;
}

interface FormStep extends StepInput {
  key: number;
}

let keyCounter = 0;
function nextKey() {
  return ++keyCounter;
}

export function RecipeForm({
  recipe,
  onSubmit,
  onCancel,
  submitLabel = "Save Recipe",
}: Props) {
  const [title, setTitle] = useState(recipe?.title ?? "");
  const [description, setDescription] = useState(recipe?.description ?? "");
  const [servings, setServings] = useState(recipe?.servings?.toString() ?? "");
  const [prepTime, setPrepTime] = useState(
    recipe?.prepTimeMinutes?.toString() ?? ""
  );
  const [cookTime, setCookTime] = useState(
    recipe?.cookTimeMinutes?.toString() ?? ""
  );
  const [sourceContext, setSourceContext] = useState(
    recipe?.sourceContext ?? ""
  );

  const [ingredients, setIngredients] = useState<FormIngredient[]>(() =>
    recipe?.ingredients?.map((i) => ({
      key: nextKey(),
      name: i.name,
      quantity: i.quantity,
      unit: i.unit,
      notes: i.notes,
    })) ?? [{ key: nextKey(), name: "", quantity: null, unit: null, notes: null }]
  );

  const [steps, setSteps] = useState<FormStep[]>(() =>
    recipe?.steps?.map((s) => ({
      key: nextKey(),
      instruction: s.instruction,
    })) ?? [{ key: nextKey(), instruction: "" }]
  );

  const [tagsInput, setTagsInput] = useState(
    recipe?.tags?.map((t) => t.tag).join(", ") ?? ""
  );

  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  function addIngredient() {
    setIngredients([
      ...ingredients,
      { key: nextKey(), name: "", quantity: null, unit: null, notes: null },
    ]);
  }

  function removeIngredient(key: number) {
    if (ingredients.length > 1) {
      setIngredients(ingredients.filter((i) => i.key !== key));
    }
  }

  function updateIngredient(key: number, updates: Partial<IngredientInput>) {
    setIngredients(
      ingredients.map((i) => (i.key === key ? { ...i, ...updates } : i))
    );
  }

  function addStep() {
    setSteps([...steps, { key: nextKey(), instruction: "" }]);
  }

  function removeStep(key: number) {
    if (steps.length > 1) {
      setSteps(steps.filter((s) => s.key !== key));
    }
  }

  function updateStep(key: number, instruction: string) {
    setSteps(steps.map((s) => (s.key === key ? { ...s, instruction } : s)));
  }

  async function handleSubmit(e: Event) {
    e.preventDefault();

    if (!title.trim()) {
      setError("Title is required");
      return;
    }

    const filteredIngredients = ingredients
      .filter((i) => i.name.trim())
      .map(({ name, quantity, unit, notes }) => ({
        name: name.trim(),
        quantity,
        unit: unit?.trim() || null,
        notes: notes?.trim() || null,
      }));

    const filteredSteps = steps
      .filter((s) => s.instruction.trim())
      .map(({ instruction }) => ({ instruction: instruction.trim() }));

    const tags: TagInput[] = tagsInput
      .split(",")
      .map((t) => t.trim())
      .filter(Boolean)
      .map((tag) => ({ tag, isAutoGenerated: false }));

    const data: CreateRecipeInput = {
      title: title.trim(),
      description: description.trim() || null,
      servings: servings ? parseInt(servings, 10) : null,
      prepTimeMinutes: prepTime ? parseInt(prepTime, 10) : null,
      cookTimeMinutes: cookTime ? parseInt(cookTime, 10) : null,
      sourceType: recipe?.sourceType ?? "text",
      sourceText: recipe?.sourceText ?? null,
      sourceContext: sourceContext.trim() || null,
      parentRecipeId: recipe?.parentRecipeId ?? null,
      ingredients: filteredIngredients,
      steps: filteredSteps,
      tags,
    };

    try {
      setSubmitting(true);
      setError(null);
      await onSubmit(data);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to save recipe");
      setSubmitting(false);
    }
  }

  return (
    <form onSubmit={handleSubmit}>
      {error && <p class="error">{error}</p>}

      <div class="form-group">
        <label for="title">Title *</label>
        <input
          id="title"
          type="text"
          value={title}
          onInput={(e) => setTitle(e.currentTarget.value)}
          placeholder="Recipe title"
          required
        />
      </div>

      <div class="form-group">
        <label for="description">Description</label>
        <textarea
          id="description"
          value={description}
          onInput={(e) => setDescription(e.currentTarget.value)}
          placeholder="A brief description of this recipe"
        />
      </div>

      <div class="form-row">
        <div class="form-group">
          <label for="servings">Servings</label>
          <input
            id="servings"
            type="number"
            min="1"
            value={servings}
            onInput={(e) => setServings(e.currentTarget.value)}
          />
        </div>
        <div class="form-group">
          <label for="prepTime">Prep time (min)</label>
          <input
            id="prepTime"
            type="number"
            min="0"
            value={prepTime}
            onInput={(e) => setPrepTime(e.currentTarget.value)}
          />
        </div>
        <div class="form-group">
          <label for="cookTime">Cook time (min)</label>
          <input
            id="cookTime"
            type="number"
            min="0"
            value={cookTime}
            onInput={(e) => setCookTime(e.currentTarget.value)}
          />
        </div>
      </div>

      <div class="form-group">
        <label>Ingredients</label>
        {ingredients.map((ing, idx) => (
          <div key={ing.key} class="ingredient-row">
            <input
              type="number"
              step="any"
              placeholder="Qty"
              value={ing.quantity ?? ""}
              onInput={(e) =>
                updateIngredient(ing.key, {
                  quantity: e.currentTarget.value
                    ? parseFloat(e.currentTarget.value)
                    : null,
                })
              }
              style="width: 80px"
            />
            <input
              type="text"
              placeholder="Unit"
              value={ing.unit ?? ""}
              onInput={(e) =>
                updateIngredient(ing.key, { unit: e.currentTarget.value || null })
              }
              style="width: 80px"
            />
            <input
              type="text"
              placeholder="Ingredient name"
              value={ing.name}
              onInput={(e) =>
                updateIngredient(ing.key, { name: e.currentTarget.value })
              }
              style="flex: 1"
            />
            <input
              type="text"
              placeholder="Notes"
              value={ing.notes ?? ""}
              onInput={(e) =>
                updateIngredient(ing.key, { notes: e.currentTarget.value || null })
              }
              style="width: 120px"
            />
            <button
              type="button"
              class="btn btn-small"
              onClick={() => removeIngredient(ing.key)}
              disabled={ingredients.length === 1}
            >
              Remove
            </button>
          </div>
        ))}
        <button type="button" class="btn" onClick={addIngredient}>
          Add Ingredient
        </button>
      </div>

      <div class="form-group">
        <label>Method</label>
        {steps.map((step, idx) => (
          <div key={step.key} class="step-row">
            <span class="step-row-number">{idx + 1}.</span>
            <textarea
              placeholder="Describe this step..."
              value={step.instruction}
              onInput={(e) => updateStep(step.key, e.currentTarget.value)}
              style="flex: 1; min-height: 60px"
            />
            <button
              type="button"
              class="btn btn-small"
              onClick={() => removeStep(step.key)}
              disabled={steps.length === 1}
            >
              Remove
            </button>
          </div>
        ))}
        <button type="button" class="btn" onClick={addStep}>
          Add Step
        </button>
      </div>

      <div class="form-group">
        <label for="tags">Tags</label>
        <input
          id="tags"
          type="text"
          value={tagsInput}
          onInput={(e) => setTagsInput(e.currentTarget.value)}
          placeholder="pasta, quick, vegetarian (comma separated)"
        />
      </div>

      <div class="form-group">
        <label for="sourceContext">Source</label>
        <input
          id="sourceContext"
          type="text"
          value={sourceContext}
          onInput={(e) => setSourceContext(e.currentTarget.value)}
          placeholder="e.g., Ottolenghi Simple p.42, or a URL"
        />
      </div>

      <div class="form-actions">
        <button type="button" class="btn" onClick={onCancel}>
          Cancel
        </button>
        <button type="submit" class="btn btn-primary" disabled={submitting}>
          {submitting ? "Saving..." : submitLabel}
        </button>
      </div>
    </form>
  );
}
