import { Router, type Response } from "express";
import { hasVariants, type ParsedRecipeResult } from "@recipes/shared";
import {
  parseRecipeFromText,
  parseRecipeFromImages,
  parseRecipeFromUrl,
  generateRecipeFromPrompt,
  type ProgressCallback,
} from "../services/recipe-parser.js";
import {
  createRecipe,
  createRecipeWithPortionVariants,
} from "../db/queries.js";

export const importRouter = Router();

interface ImportOutcome {
  recipe: ParsedRecipeResult;
  sourceType: "photo" | "url" | "text";
  sourceText: string | null;
  sourceContext: string | null;
}

function saveRecipeResult(outcome: ImportOutcome): number[] {
  const { recipe, sourceType, sourceText, sourceContext } = outcome;

  if (hasVariants(recipe)) {
    return createRecipeWithPortionVariants(
      recipe,
      sourceType,
      sourceText,
      sourceContext
    );
  }

  return [
    createRecipe({
      title: recipe.title,
      description: recipe.description,
      servings: recipe.servings,
      prepTimeMinutes: recipe.prepTimeMinutes,
      cookTimeMinutes: recipe.cookTimeMinutes,
      sourceType,
      sourceText,
      sourceContext,
      ingredients: recipe.ingredients,
      steps: recipe.steps,
      tags: recipe.suggestedTags.map((tag) => ({
        tag,
        isAutoGenerated: true,
      })),
    }),
  ];
}

/**
 * Run an import as an SSE stream: report progress, save the parsed recipe, then
 * report the new IDs. The client may walk away mid-import; the recipe still saves
 * and shows up in the list.
 */
async function streamImport(
  res: Response,
  run: (progress: ProgressCallback) => Promise<ImportOutcome>
): Promise<void> {
  res.setHeader("Content-Type", "text/event-stream");
  res.setHeader("Cache-Control", "no-cache");
  res.setHeader("Connection", "keep-alive");
  res.flushHeaders();

  const send = (data: Record<string, unknown>) => {
    res.write(`data: ${JSON.stringify(data)}\n\n`);
  };

  try {
    const outcome = await run((stage, message) => send({ stage, message }));

    send({ stage: "saving", message: "Saving recipe..." });
    const recipeIds = saveRecipeResult(outcome);

    send({
      stage: "complete",
      message: "Recipe saved",
      data: { recipeIds, title: outcome.recipe.title },
    });
  } catch (err) {
    send({
      stage: "error",
      message: err instanceof Error ? err.message : "Import failed",
    });
  }

  res.end();
}

async function fetchPage(url: string): Promise<string> {
  const response = await fetch(url, {
    headers: {
      "User-Agent": "Mozilla/5.0 (compatible; RecipeBot/1.0; +http://localhost)",
      Accept: "text/html,application/xhtml+xml",
    },
  });

  if (!response.ok) {
    throw new Error(`Failed to fetch URL: ${response.statusText}`);
  }

  return response.text();
}

// POST /api/import/url/queue - Import from URL and auto-save
importRouter.post("/url/queue", async (req, res) => {
  const { url } = req.body;

  if (!url || typeof url !== "string") {
    return res.status(400).json({ error: "URL is required" });
  }

  await streamImport(res, async (progress) => {
    progress("fetching", "Fetching recipe page...");
    const html = await fetchPage(url);

    const { extractedText, recipe } = await parseRecipeFromUrl(html, progress);
    return {
      recipe,
      sourceType: "url",
      sourceText: extractedText,
      sourceContext: url,
    };
  });
});

// POST /api/import/photos/queue - Import from photos and auto-save
importRouter.post("/photos/queue", async (req, res) => {
  const { images } = req.body;

  if (!Array.isArray(images) || images.length === 0) {
    return res.status(400).json({ error: "At least one image is required" });
  }

  await streamImport(res, async (progress) => {
    const { extractedText, recipe } = await parseRecipeFromImages(
      images,
      progress
    );
    return {
      recipe,
      sourceType: "photo",
      sourceText: extractedText,
      sourceContext: null,
    };
  });
});

// POST /api/import/text/queue - Import from pasted text and auto-save
importRouter.post("/text/queue", async (req, res) => {
  const { text } = req.body;

  if (!text || typeof text !== "string") {
    return res.status(400).json({ error: "Text is required" });
  }

  await streamImport(res, async (progress) => {
    const recipe = await parseRecipeFromText(text, progress);
    return {
      recipe,
      sourceType: "text",
      sourceText: text,
      sourceContext: null,
    };
  });
});

// POST /api/import/generate - Generate a new recipe from a prompt
importRouter.post("/generate", async (req, res, next) => {
  try {
    const { prompt } = req.body;

    if (!prompt || typeof prompt !== "string") {
      return res.status(400).json({ error: "Prompt is required" });
    }

    const recipe = await generateRecipeFromPrompt(prompt);

    res.json({
      sourceType: "text",
      sourceText: null,
      sourceContext: `Generated from prompt: ${prompt}`,
      recipe,
    });
  } catch (err) {
    next(err);
  }
});
