import { useState, useRef } from "preact/hooks";
import { route } from "preact-router";
import { RecipeForm } from "../components/RecipeForm";
import {
  createRecipe,
  importFromUrl,
  importFromPhotos,
  importFromText,
  type ImportResult,
} from "../api/client";
import type { CreateRecipeInput, ParsedRecipe } from "@recipes/shared";

type Mode = "choose" | "manual" | "photo" | "url" | "text" | "review";

interface ImportState {
  sourceType: "photo" | "url" | "text";
  sourceText: string;
  sourceContext: string | null;
  recipe: ParsedRecipe;
}

export function AddRecipe() {
  const [mode, setMode] = useState<Mode>("choose");
  const [importState, setImportState] = useState<ImportState | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // URL import state
  const [urlInput, setUrlInput] = useState("");

  // Text import state
  const [textInput, setTextInput] = useState("");

  // Photo import state
  const [photos, setPhotos] = useState<string[]>([]);
  const fileInputRef = useRef<HTMLInputElement>(null);

  async function handleSubmit(data: CreateRecipeInput) {
    const recipe = await createRecipe(data);
    route(`/recipe/${recipe.id}`);
  }

  async function handleImportFromUrl() {
    if (!urlInput.trim()) {
      setError("Please enter a URL");
      return;
    }

    try {
      setLoading(true);
      setError(null);
      const result = await importFromUrl(urlInput.trim());
      setImportState(result);
      setMode("review");
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to import from URL");
    } finally {
      setLoading(false);
    }
  }

  async function handleImportFromText() {
    if (!textInput.trim()) {
      setError("Please enter some recipe text");
      return;
    }

    try {
      setLoading(true);
      setError(null);
      const result = await importFromText(textInput.trim());
      setImportState(result);
      setMode("review");
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to parse text");
    } finally {
      setLoading(false);
    }
  }

  function handlePhotoSelect(e: Event) {
    const input = e.target as HTMLInputElement;
    if (!input.files?.length) return;

    const newPhotos: string[] = [];
    const readers: Promise<void>[] = [];

    for (const file of Array.from(input.files)) {
      const reader = new FileReader();
      readers.push(
        new Promise((resolve) => {
          reader.onload = () => {
            if (typeof reader.result === "string") {
              newPhotos.push(reader.result);
            }
            resolve();
          };
          reader.readAsDataURL(file);
        })
      );
    }

    Promise.all(readers).then(() => {
      setPhotos((prev) => [...prev, ...newPhotos]);
    });

    input.value = "";
  }

  function removePhoto(index: number) {
    setPhotos((prev) => prev.filter((_, i) => i !== index));
  }

  async function handleImportFromPhotos() {
    if (photos.length === 0) {
      setError("Please add at least one photo");
      return;
    }

    try {
      setLoading(true);
      setError(null);
      const result = await importFromPhotos(photos);
      setImportState(result);
      setMode("review");
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to extract from photos");
    } finally {
      setLoading(false);
    }
  }

  function handleBack() {
    setMode("choose");
    setError(null);
    setImportState(null);
  }

  // Review/Edit imported recipe
  if (mode === "review" && importState) {
    const initialData: Partial<CreateRecipeInput> = {
      title: importState.recipe.title,
      description: importState.recipe.description,
      servings: importState.recipe.servings,
      prepTimeMinutes: importState.recipe.prepTimeMinutes,
      cookTimeMinutes: importState.recipe.cookTimeMinutes,
      sourceType: importState.sourceType,
      sourceText: importState.sourceText,
      sourceContext: importState.sourceContext,
      ingredients: importState.recipe.ingredients,
      steps: importState.recipe.steps,
      tags: importState.recipe.suggestedTags.map((tag) => ({
        tag,
        isAutoGenerated: true,
      })),
    };

    return (
      <div class="page">
        <header class="header">
          <button class="btn" onClick={handleBack}>
            Back
          </button>
          <h1>Review Imported Recipe</h1>
        </header>
        <main>
          <p class="import-success">
            Recipe extracted successfully. Review and edit before saving.
          </p>
          <RecipeForm
            recipe={initialData as CreateRecipeInput}
            onSubmit={handleSubmit}
            onCancel={handleBack}
            submitLabel="Save Recipe"
          />
        </main>
      </div>
    );
  }

  // Manual entry
  if (mode === "manual") {
    return (
      <div class="page">
        <header class="header">
          <button class="btn" onClick={handleBack}>
            Back
          </button>
          <h1>Add Recipe Manually</h1>
        </header>
        <main>
          <RecipeForm
            onSubmit={handleSubmit}
            onCancel={handleBack}
            submitLabel="Create Recipe"
          />
        </main>
      </div>
    );
  }

  // Photo import
  if (mode === "photo") {
    return (
      <div class="page">
        <header class="header">
          <button class="btn" onClick={handleBack}>
            Back
          </button>
          <h1>Import from Photo</h1>
        </header>
        <main>
          {error && <p class="error">{error}</p>}

          <div class="form-group">
            <label>Photos</label>
            <input
              ref={fileInputRef}
              type="file"
              accept="image/*"
              multiple
              onChange={handlePhotoSelect}
              style="display: none"
            />
            <button
              class="btn"
              onClick={() => fileInputRef.current?.click()}
              disabled={loading}
            >
              Add Photos
            </button>
          </div>

          {photos.length > 0 && (
            <div class="photo-grid">
              {photos.map((photo, idx) => (
                <div key={idx} class="photo-preview">
                  <img src={photo} alt={`Photo ${idx + 1}`} />
                  <button
                    class="photo-remove"
                    onClick={() => removePhoto(idx)}
                    disabled={loading}
                  >
                    Remove
                  </button>
                </div>
              ))}
            </div>
          )}

          <div class="form-actions">
            <button class="btn" onClick={handleBack} disabled={loading}>
              Cancel
            </button>
            <button
              class="btn btn-primary"
              onClick={handleImportFromPhotos}
              disabled={loading || photos.length === 0}
            >
              {loading ? "Extracting..." : "Extract Recipe"}
            </button>
          </div>
        </main>
      </div>
    );
  }

  // URL import
  if (mode === "url") {
    return (
      <div class="page">
        <header class="header">
          <button class="btn" onClick={handleBack}>
            Back
          </button>
          <h1>Import from URL</h1>
        </header>
        <main>
          {error && <p class="error">{error}</p>}

          <div class="form-group">
            <label for="url-input">Recipe URL</label>
            <input
              id="url-input"
              type="url"
              value={urlInput}
              onInput={(e) => setUrlInput(e.currentTarget.value)}
              placeholder="https://example.com/recipe"
              disabled={loading}
            />
          </div>

          <div class="form-actions">
            <button class="btn" onClick={handleBack} disabled={loading}>
              Cancel
            </button>
            <button
              class="btn btn-primary"
              onClick={handleImportFromUrl}
              disabled={loading || !urlInput.trim()}
            >
              {loading ? "Importing..." : "Import Recipe"}
            </button>
          </div>
        </main>
      </div>
    );
  }

  // Text import
  if (mode === "text") {
    return (
      <div class="page">
        <header class="header">
          <button class="btn" onClick={handleBack}>
            Back
          </button>
          <h1>Import from Text</h1>
        </header>
        <main>
          {error && <p class="error">{error}</p>}

          <div class="form-group">
            <label for="text-input">Paste recipe text</label>
            <textarea
              id="text-input"
              value={textInput}
              onInput={(e) => setTextInput(e.currentTarget.value)}
              placeholder="Paste the recipe text here..."
              rows={12}
              disabled={loading}
            />
          </div>

          <div class="form-actions">
            <button class="btn" onClick={handleBack} disabled={loading}>
              Cancel
            </button>
            <button
              class="btn btn-primary"
              onClick={handleImportFromText}
              disabled={loading || !textInput.trim()}
            >
              {loading ? "Processing..." : "Process Recipe"}
            </button>
          </div>
        </main>
      </div>
    );
  }

  // Choose method
  return (
    <div class="page">
      <header class="header">
        <a href="/" class="btn">
          Back
        </a>
        <h1>Add Recipe</h1>
      </header>
      <main class="add-recipe">
        <p>Choose how to add your recipe:</p>
        <div class="input-methods">
          <button class="btn btn-large" onClick={() => setMode("photo")}>
            Take Photo
          </button>
          <button class="btn btn-large" onClick={() => setMode("url")}>
            Import from URL
          </button>
          <button class="btn btn-large" onClick={() => setMode("text")}>
            Paste Text
          </button>
          <button
            class="btn btn-large btn-primary"
            onClick={() => setMode("manual")}
          >
            Enter Manually
          </button>
        </div>
      </main>
    </div>
  );
}
