import { useEffect, useState, useMemo } from "preact/hooks";
import { route } from "preact-router";
import type { RecipeWithDetails, ParsedRecipe } from "@recipes/shared";
import {
  getRecipe,
  getRecipes,
  updateRating,
  deleteRecipe,
  createRecipe,
  updateRecipe,
} from "../api/client";
import { ScalingControls } from "../components/ScalingControls";
import { Timer } from "../components/Timer";
import { ChatModal } from "../components/ChatModal";
import { useTimer } from "../hooks/useTimer";
import { useWakeLock } from "../hooks/useWakeLock";
import { useCookingList } from "../hooks/useCookingList";
import {
  formatQuantity,
  renderStepText,
  extractTimers,
} from "../utils/scaling";

interface Props {
  id?: string;
  path?: string;
}

function formatDuration(minutes: number | null): string | null {
  if (!minutes) return null;
  if (minutes < 60) return `${minutes} min`;
  const hours = Math.floor(minutes / 60);
  const mins = minutes % 60;
  return mins > 0 ? `${hours}h ${mins}m` : `${hours}h`;
}

function shuffleArray<T>(array: T[]): T[] {
  const shuffled = [...array];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
}

export function RecipeDetail({ id }: Props) {
  const [recipe, setRecipe] = useState<RecipeWithDetails | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [checkedIngredients, setCheckedIngredients] = useState<Set<number>>(
    new Set()
  );
  const [showDeleteConfirm, setShowDeleteConfirm] = useState(false);
  const [showChat, setShowChat] = useState(false);
  const [currentServings, setCurrentServings] = useState<number>(1);

  const { timers, startTimer, stopTimer, resetTimer, getTimer } = useTimer();
  const wakeLock = useWakeLock();
  const cookingList = useCookingList();

  useEffect(() => {
    if (id) {
      loadRecipe(parseInt(id, 10));
    }
  }, [id]);

  async function loadRecipe(recipeId: number) {
    try {
      setLoading(true);
      setError(null);
      const data = await getRecipe(recipeId);
      setRecipe(data);
      setCurrentServings(data.servings || 1);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to load recipe");
    } finally {
      setLoading(false);
    }
  }

  const baseServings = recipe?.servings || 1;
  const scale = currentServings / baseServings;

  // Shuffle variants once when recipe loads
  const shuffledVariants = useMemo(
    () => (recipe?.variants ? shuffleArray(recipe.variants) : []),
    [recipe?.variants]
  );

  async function handleRatingChange(rating: "meh" | "good" | "great" | null) {
    if (!recipe) return;
    const newRating = recipe.rating === rating ? null : rating;
    try {
      await updateRating(recipe.id, newRating);
      setRecipe({ ...recipe, rating: newRating });
    } catch (err) {
      console.error("Failed to update rating:", err);
    }
  }

  function toggleIngredient(ingredientId: number) {
    setCheckedIngredients((prev) => {
      const next = new Set(prev);
      if (next.has(ingredientId)) {
        next.delete(ingredientId);
      } else {
        next.add(ingredientId);
      }
      return next;
    });
  }

  async function handleDelete() {
    if (!recipe) return;
    try {
      await deleteRecipe(recipe.id);
      route("/");
    } catch (err) {
      console.error("Failed to delete recipe:", err);
    }
  }

  async function handleSaveAsNew(parsed: ParsedRecipe) {
    try {
      const newRecipe = await createRecipe({
        title: parsed.title,
        description: parsed.description,
        servings: parsed.servings,
        prepTimeMinutes: parsed.prepTimeMinutes,
        cookTimeMinutes: parsed.cookTimeMinutes,
        sourceType: "text",
        sourceText: null,
        sourceContext: recipe ? `Modified from: ${recipe.title}` : null,
        ingredients: parsed.ingredients,
        steps: parsed.steps,
        tags: parsed.suggestedTags.map((tag) => ({
          tag,
          isAutoGenerated: true,
        })),
      });
      setShowChat(false);
      route(`/recipe/${newRecipe.id}`);
    } catch (err) {
      console.error("Failed to save recipe:", err);
    }
  }

  async function handleSaveAsVariant(parsed: ParsedRecipe) {
    if (!recipe) return;
    try {
      const newRecipe = await createRecipe({
        title: parsed.title,
        description: parsed.description,
        servings: parsed.servings,
        prepTimeMinutes: parsed.prepTimeMinutes,
        cookTimeMinutes: parsed.cookTimeMinutes,
        sourceType: "text",
        sourceText: null,
        sourceContext: `Variant of: ${recipe.title}`,
        parentRecipeId: recipe.id,
        ingredients: parsed.ingredients,
        steps: parsed.steps,
        tags: parsed.suggestedTags.map((tag) => ({
          tag,
          isAutoGenerated: true,
        })),
      });
      setShowChat(false);
      route(`/recipe/${newRecipe.id}`);
    } catch (err) {
      console.error("Failed to save variant:", err);
    }
  }

  async function handleReplaceRecipe(parsed: ParsedRecipe) {
    if (!recipe) return;
    try {
      await updateRecipe(recipe.id, {
        title: parsed.title,
        description: parsed.description,
        servings: parsed.servings,
        prepTimeMinutes: parsed.prepTimeMinutes,
        cookTimeMinutes: parsed.cookTimeMinutes,
        ingredients: parsed.ingredients,
        steps: parsed.steps,
        tags: parsed.suggestedTags.map((tag) => ({
          tag,
          isAutoGenerated: true,
        })),
      });
      setShowChat(false);
      loadRecipe(recipe.id);
    } catch (err) {
      console.error("Failed to update recipe:", err);
    }
  }

  async function handleSurpriseMe() {
    try {
      const allRecipes = await getRecipes();
      const candidates = allRecipes.filter(
        (r) => r.parentRecipeId === null && r.id !== recipe?.id
      );
      if (candidates.length > 0) {
        const random = candidates[Math.floor(Math.random() * candidates.length)];
        route(`/recipe/${random.id}`);
      }
    } catch (err) {
      console.error("Failed to surprise me:", err);
    }
  }

  if (loading) {
    return (
      <div class="page">
        <p class="loading">Loading recipe...</p>
      </div>
    );
  }

  if (error || !recipe) {
    return (
      <div class="page">
        <header class="header">
          <a href="/" class="btn">
            Back
          </a>
          <h1>Error</h1>
        </header>
        <p class="error">{error || "Recipe not found"}</p>
      </div>
    );
  }

  return (
    <div class="page recipe-detail">
      <header class="header">
        <a href="/" class="btn">
          Back
        </a>
        <h1>{recipe.title}</h1>
        <div class="header-actions">
          <button
            class="btn"
            onClick={handleSurpriseMe}
            title="Show me another random recipe"
          >
            🎲
          </button>
          <a href={`/edit/${recipe.id}`} class="btn">
            Edit
          </a>
          <button
            class="btn btn-danger"
            onClick={() => setShowDeleteConfirm(true)}
          >
            Delete
          </button>
        </div>
      </header>

      <main>
        {recipe.parentRecipe && (
          <a href={`/recipe/${recipe.parentRecipe.id}`} class="parent-recipe-link">
            ← Variant of: {recipe.parentRecipe.title}
          </a>
        )}

        {recipe.description && (
          <p class="recipe-description">{recipe.description}</p>
        )}

        <div class="recipe-meta">
          {recipe.prepTimeMinutes && (
            <span>Prep: {formatDuration(recipe.prepTimeMinutes)}</span>
          )}
          {recipe.cookTimeMinutes && (
            <span>Cook: {formatDuration(recipe.cookTimeMinutes)}</span>
          )}
          {recipe.servings && <span>Serves {recipe.servings}</span>}
        </div>

        <div class="recipe-controls">
          <div class="rating-buttons">
            <button
              class={`rating-btn rating-meh ${recipe.rating === "meh" ? "active" : ""}`}
              onClick={() => handleRatingChange("meh")}
              title="Meh"
            >
              👎
            </button>
            <button
              class={`rating-btn rating-good ${recipe.rating === "good" ? "active" : ""}`}
              onClick={() => handleRatingChange("good")}
              title="Good"
            >
              👍
            </button>
            <button
              class={`rating-btn rating-great ${recipe.rating === "great" ? "active" : ""}`}
              onClick={() => handleRatingChange("great")}
              title="Great"
            >
              <span class="thumbs-double">
                <span class="thumb-back">👍</span>
                <span class="thumb-front">👍</span>
              </span>
            </button>
          </div>

          {wakeLock.isSupported && (
            <button
              class={`btn wake-lock-btn ${wakeLock.isActive ? "active" : ""}`}
              onClick={wakeLock.toggle}
            >
              {wakeLock.isActive ? "Screen On" : "Keep Awake"}
            </button>
          )}

          {cookingList.isInList(recipe.id) ? (
            <button
              class="btn"
              onClick={() => cookingList.removeRecipe(recipe.id)}
            >
              Remove from List
            </button>
          ) : (
            <button
              class="btn btn-primary"
              onClick={() =>
                cookingList.addRecipe(recipe.id, recipe.title, currentServings)
              }
            >
              Add to List
            </button>
          )}

          <button class="btn" onClick={() => setShowChat(true)}>
            Chat
          </button>
        </div>

        {recipe.tags.length > 0 && (
          <div class="recipe-tags">
            {recipe.tags.map((t) => (
              <span key={t.id} class="tag-chip">
                {t.tag}
              </span>
            ))}
          </div>
        )}

        {shuffledVariants.length > 0 && (
          <div class="variants-section">
            <h3 class="variants-title">Variants</h3>
            <div class="variants-carousel">
              {shuffledVariants.map((v) => (
                <a key={v.id} href={`/recipe/${v.id}`} class="variant-card">
                  <div class="variant-card-content">
                    <span class="variant-card-title">{v.title}</span>
                    {v.description && (
                      <span class="variant-card-description">
                        {v.description}
                      </span>
                    )}
                  </div>
                </a>
              ))}
            </div>
          </div>
        )}

        {recipe.servings && (
          <ScalingControls
            baseServings={baseServings}
            currentServings={currentServings}
            onServingsChange={setCurrentServings}
          />
        )}

        {recipe.ingredients.length > 0 && (
          <section class="recipe-section">
            <h2>Ingredients</h2>
            <ul class="ingredient-list">
              {recipe.ingredients.map((ing) => (
                <li key={ing.id} class="ingredient-item">
                  <input
                    type="checkbox"
                    class="ingredient-checkbox"
                    checked={checkedIngredients.has(ing.id)}
                    onChange={() => toggleIngredient(ing.id)}
                  />
                  <span class="ingredient-quantity">
                    {ing.quantity !== null
                      ? formatQuantity(ing.quantity, ing.unit, scale)
                      : ""}
                  </span>
                  <span class="ingredient-name">{ing.name}</span>
                  {ing.notes && (
                    <span class="ingredient-notes">({ing.notes})</span>
                  )}
                </li>
              ))}
            </ul>
          </section>
        )}

        {recipe.steps.length > 0 && (
          <section class="recipe-section">
            <h2>Method</h2>
            <ol class="step-list">
              {recipe.steps.map((step, idx) => {
                const stepTimers = extractTimers(step.instruction);
                const renderedText = renderStepText(step.instruction, scale);

                return (
                  <li key={step.id} class="step-item">
                    <span class="step-number">{idx + 1}</span>
                    <div class="step-content">
                      <p>{renderedText}</p>
                      {stepTimers.map((t, timerIdx) => {
                        const timerId = `step-${step.id}-timer-${timerIdx}`;
                        const timer = getTimer(timerId);

                        return (
                          <Timer
                            key={timerId}
                            timer={timer}
                            minutes={t.minutes}
                            onStart={() => startTimer(timerId, t.minutes)}
                            onStop={() => stopTimer(timerId)}
                            onReset={() => resetTimer(timerId)}
                          />
                        );
                      })}
                    </div>
                  </li>
                );
              })}
            </ol>
          </section>
        )}

        {recipe.sourceContext && (
          <section class="recipe-section">
            <h2>Source</h2>
            <p>{recipe.sourceContext}</p>
          </section>
        )}

      </main>

      {showDeleteConfirm && (
        <div
          class="confirm-overlay"
          onClick={() => setShowDeleteConfirm(false)}
        >
          <div class="confirm-dialog" onClick={(e) => e.stopPropagation()}>
            <h3>Delete Recipe?</h3>
            <p>
              Are you sure you want to delete "{recipe.title}"? This cannot be
              undone.
            </p>
            <div class="confirm-actions">
              <button class="btn" onClick={() => setShowDeleteConfirm(false)}>
                Cancel
              </button>
              <button class="btn btn-danger" onClick={handleDelete}>
                Delete
              </button>
            </div>
          </div>
        </div>
      )}

      <ChatModal
        recipeId={recipe.id}
        recipeTitle={recipe.title}
        isOpen={showChat}
        onClose={() => setShowChat(false)}
        onSaveAsNew={handleSaveAsNew}
        onSaveAsVariant={handleSaveAsVariant}
        onReplaceRecipe={handleReplaceRecipe}
      />
    </div>
  );
}
