// Core types

export interface Recipe {
  id: number;
  title: string;
  description: string | null;
  servings: number | null;
  prepTimeMinutes: number | null;
  cookTimeMinutes: number | null;
  rating: "meh" | "good" | "great" | null;
  sourceType: "photo" | "url" | "text";
  sourceText: string | null;
  sourceContext: string | null;
  parentRecipeId: number | null;
  createdAt: string;
  updatedAt: string;
}

export interface Ingredient {
  id: number;
  recipeId: number;
  position: number;
  name: string;
  quantity: number | null;
  unit: string | null;
  notes: string | null;
}

export interface Step {
  id: number;
  recipeId: number;
  position: number;
  instruction: string; // Contains {{qty:N}} and {{timer:M}} markers
}

export interface Tag {
  id: number;
  recipeId: number;
  tag: string;
  isAutoGenerated: boolean;
}

// Minimal recipe info for parent/variant references
export interface RecipeRef {
  id: number;
  title: string;
}

// Full recipe with relations
export interface RecipeWithDetails extends Recipe {
  ingredients: Ingredient[];
  steps: Step[];
  tags: Tag[];
  variants?: Recipe[];
  parentRecipe?: RecipeRef;
}

// Input types for creating/updating

export interface IngredientInput {
  name: string;
  quantity?: number | null;
  unit?: string | null;
  notes?: string | null;
}

export interface StepInput {
  instruction: string;
}

export interface TagInput {
  tag: string;
  isAutoGenerated?: boolean;
}

export interface CreateRecipeInput {
  title: string;
  description?: string | null;
  servings?: number | null;
  prepTimeMinutes?: number | null;
  cookTimeMinutes?: number | null;
  rating?: "meh" | "good" | "great" | null;
  sourceType: "photo" | "url" | "text";
  sourceText?: string | null;
  sourceContext?: string | null;
  parentRecipeId?: number | null;
  ingredients?: IngredientInput[];
  steps?: StepInput[];
  tags?: TagInput[];
}

// LLM parsed recipe output
export interface ParsedRecipe {
  title: string;
  description: string | null;
  servings: number | null;
  prepTimeMinutes: number | null;
  cookTimeMinutes: number | null;
  ingredients: IngredientInput[];
  steps: StepInput[];
  suggestedTags: string[];
}

// Chat types
export interface ChatMessage {
  role: "user" | "assistant";
  content: string;
  createdAt: string;
}

export interface ChatResponse {
  message: string;
  updatedRecipe: ParsedRecipe | null;
}
