// Core types

export type VariantType = "portion" | "content";

export interface Recipe {
  id: number;
  title: string;
  description: string | null;
  servings: number | null;
  prepTimeMinutes: number | null;
  cookTimeMinutes: number | null;
  rating: "meh" | "good" | "great" | null;
  sourceType: "photo" | "url" | "text";
  sourceText: string | null;
  sourceContext: string | null;
  parentRecipeId: number | null;
  variantType: VariantType | null;
  createdAt: string;
  updatedAt: string;
}

export interface Ingredient {
  id: number;
  recipeId: number;
  position: number;
  name: string;
  quantity: number | null;
  unit: string | null;
  notes: string | null;
}

export interface Step {
  id: number;
  recipeId: number;
  position: number;
  instruction: string; // Contains {{qty:N}} and {{timer:M}} markers
}

export interface Tag {
  id: number;
  recipeId: number;
  tag: string;
  isAutoGenerated: boolean;
}

// Minimal recipe info for parent/variant references
export interface RecipeRef {
  id: number;
  title: string;
}

// Portion variant reference (just servings and id for picker)
export interface PortionVariantRef {
  id: number;
  servings: number;
}

// Full recipe with relations
export interface RecipeWithDetails extends Recipe {
  ingredients: Ingredient[];
  steps: Step[];
  tags: Tag[];
  portionVariants?: PortionVariantRef[]; // Other portion sizes available
  contentVariants?: Recipe[]; // Different versions (e.g., vegetarian)
  parentRecipe?: RecipeRef;
}

// Input types for creating/updating

export interface IngredientInput {
  name: string;
  quantity?: number | null;
  unit?: string | null;
  notes?: string | null;
}

export interface StepInput {
  instruction: string;
}

export interface TagInput {
  tag: string;
  isAutoGenerated?: boolean;
}

export interface CreateRecipeInput {
  title: string;
  description?: string | null;
  servings?: number | null;
  prepTimeMinutes?: number | null;
  cookTimeMinutes?: number | null;
  rating?: "meh" | "good" | "great" | null;
  sourceType: "photo" | "url" | "text";
  sourceText?: string | null;
  sourceContext?: string | null;
  parentRecipeId?: number | null;
  variantType?: VariantType | null;
  ingredients?: IngredientInput[];
  steps?: StepInput[];
  tags?: TagInput[];
}

// LLM parsed recipe output
export interface ParsedRecipe {
  title: string;
  description: string | null;
  servings: number | null;
  prepTimeMinutes: number | null;
  cookTimeMinutes: number | null;
  ingredients: IngredientInput[];
  steps: StepInput[];
  suggestedTags: string[];
  parentRecipeId?: number | null; // For chat-generated variants
  variantType?: VariantType | null; // For chat-generated portion variants
}

// Single portion variant from parser (shares title/description/tags with siblings)
export interface ParsedPortionVariant {
  servings: number;
  prepTimeMinutes: number | null;
  cookTimeMinutes: number | null;
  ingredients: IngredientInput[];
  steps: StepInput[];
}

// Multi-variant parser output when recipe has multiple portion sizes
export interface ParsedRecipeWithVariants {
  title: string;
  description: string | null;
  suggestedTags: string[];
  variants: ParsedPortionVariant[];
}

// Union type for parser output
export type ParsedRecipeResult = ParsedRecipe | ParsedRecipeWithVariants;

// Type guard to check if result has variants
export function hasVariants(
  result: ParsedRecipeResult
): result is ParsedRecipeWithVariants {
  return "variants" in result && Array.isArray(result.variants);
}

// Chat types
export interface ChatMessage {
  role: "user" | "assistant";
  content: string;
  createdAt: string;
}

export interface ChatResponse {
  message: string;
  updatedRecipe: ParsedRecipe | null;
}
